# Builds Bridge Talk: the application executable and the bespoke setup program.
#
#   ./build.ps1                 build the application and the setup program
#   ./build.ps1 -SkipInstaller  build only the application
#
# Outputs:
#   build/bin/BridgeTalk.exe                 the application
#   dist-installer/BridgeTalkSetup.exe       the setup program, carrying the
#                                                application and the model files as an
#                                                embedded payload
#
# The version is read from VERSION and passed into the setup program with -ldflags,
# so no version literal lives anywhere in the source. Note that -X only reaches a
# var; against a const it silently does nothing, which is why appVersion is a var.
param(
    [switch]$SkipInstaller
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$version = (Get-Content (Join-Path $root 'VERSION')).Trim()
Write-Host "Building Bridge Talk $version"

# The site shows the version only through delimited tokens, so the build stamps them
# from VERSION before the gate runs. A site left showing an older number than the setup
# program it links to is a quiet error that nobody catches by eye.
Write-Host 'Stamping the version into the site...'
python stamp_version.py
if ($LASTEXITCODE -ne 0) { throw "stamp_version.py failed with exit code $LASTEXITCODE" }

# Cgo is pinned off rather than left to whatever the machine happens to default to.
# The audio path decodes and plays in pure Go and nothing else here wants a C
# toolchain, so there is nothing to lose by disabling it. Off is already the default
# on a machine with no C compiler, which is precisely why leaving it implicit is a
# trap: the first machine with one would quietly start producing a different binary
# and nothing would say so. It is set before the gate as well as the build, so the
# tests exercise the configuration that ships.
$env:CGO_ENABLED = '0'

# Verify before building, with no way past it. A gate that can be skipped is a gate
# that is skipped on the day it would have caught something, so there is no switch to
# turn this off: run test.ps1 directly while working; let the build insist. The build also
# measures making a complete script (NFR-P-203, NFR-C-502), which the everyday gate leaves to
# -Benchmarks because it takes minutes (Oliver, 2026-09-14).
& (Join-Path $root 'test.ps1') -Benchmarks
if ($LASTEXITCODE -ne 0) { throw "test.ps1 failed with exit code $LASTEXITCODE" }

# One icon is the whole identity: the application executable, the setup executable,
# the Start Menu and Desktop shortcuts, the taskbar button and the tray icon all end
# up wearing it. The shortcuts, the taskbar and the tray each read it out of the
# binary rather than carrying a copy, so placing it on the two executables is the
# whole job.
#
# The .ico is generated by tools/genicons.py and committed, rather than left for
# Wails to derive from appicon.png at build time. Wails only derives one when the
# file is absent, so relying on that would mean deleting and hoping; copying a known
# file leaves nothing to hope about.
# The setup window's own header mark is not handled here: tools/genicons.py writes
# it straight into the setup page's directory, small enough to load as it is. That
# copy is committed alongside the page.
$master = Join-Path $root 'assets/application-icon.png'
$masterIco = Join-Path $root 'assets/application-icon.ico'
if (-not ((Test-Path $master) -and (Test-Path $masterIco))) {
    throw 'Missing assets/application-icon.png or .ico: run tools/genicons.py first.'
}
Write-Host 'Applying the application icon...'
foreach ($dir in @('build', 'installer/build')) {
    New-Item -ItemType Directory -Force -Path (Join-Path $root "$dir/windows") | Out-Null
    Copy-Item $master (Join-Path $root "$dir/appicon.png") -Force
    Copy-Item $masterIco (Join-Path $root "$dir/windows/icon.ico") -Force
}

Write-Host 'Building the application...'
wails build
if ($LASTEXITCODE -ne 0) { throw "wails build failed with exit code $LASTEXITCODE" }

if ($SkipInstaller) {
    Write-Host 'Done: build/bin/BridgeTalk.exe'
    exit 0
}

Write-Host 'Packing the application and the model files as the setup payload...'
$payload = Join-Path $root 'installer/payload.zip'
# tools/payload checks models/ against the list before it packs anything, downloading nothing,
# then takes from it every file the application reads beside itself (FR-543). The list is the one
# place those files are named, so nothing here names them again. The archive is written whole: a
# packing that is refused leaves the placeholder where it was.
go run ./tools/payload -app (Join-Path $root 'build/bin') -out $payload
if ($LASTEXITCODE -ne 0) { throw "tools/payload failed with exit code $LASTEXITCODE" }

try {
    Write-Host 'Building the setup program...'
    Push-Location (Join-Path $root 'installer')
    try {
        wails build -ldflags "-X main.appVersion=$version"
        if ($LASTEXITCODE -ne 0) { throw "wails build failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }

    Write-Host 'Collecting the setup program...'
    $distDir = Join-Path $root 'dist-installer'
    New-Item -ItemType Directory -Force -Path $distDir | Out-Null
    $built = Join-Path $root 'installer/build/bin/BridgeTalkSetup.exe'
    Copy-Item $built (Join-Path $distDir 'BridgeTalkSetup.exe') -Force
} finally {
    # Put the empty-zip placeholder back whether or not the setup program built, so
    # `go build ./...` and the tests keep working without a full build and a payload of
    # over 300 MB is never left where a commit could pick it up.
    $empty = [byte[]](0x50, 0x4B, 0x05, 0x06) + (New-Object byte[] 18)
    [System.IO.File]::WriteAllBytes($payload, $empty)
}

Write-Host "Done: dist-installer/BridgeTalkSetup.exe ($version)"
