package config

import (
	_ "embed"
	"fmt"

	"github.com/oernster/bridge-talk/internal/domain/cue"
	"github.com/oernster/bridge-talk/internal/domain/pause"
	"github.com/oernster/bridge-talk/internal/infrastructure/tomlfile"
)

//go:embed pauses.toml
var embeddedPauses []byte

// pausesHeader opens pauses.toml, saying whose file it is and how it is made again.
const pausesHeader = "# The pause before a final commander in each machine voice's joined lines, made by the pauses tool (FR-551).\n" +
	madeAgain

// madeAgain closes the header of each file the pauses tool writes, saying how it is made again.
const madeAgain = "# Do not edit this file: after the saved speech sounds or the model files change, from the repository root run\n" +
	"#   go run ./tools/pauses\n\n"

// pausesFile is the shape of pauses.toml: the silence a pause inserts, the digest of the model the
// pauses were found with and each voice's pauses under [voices.<id>]. A key is left out when it is
// zero or empty, so the empty book is written as the header alone.
type pausesFile struct {
	Silence int                    `toml:"silence,omitzero"`
	Model   string                 `toml:"model,omitempty"`
	Voices  map[string]pausesVoice `toml:"voices,omitempty"`
}

// pausesVoice is one voice's pauses: the digest of its style file, then one [[voices.<id>.lines]]
// table for each line in the book's order.
type pausesVoice struct {
	Style string       `toml:"style"`
	Lines []pausesLine `toml:"lines"`
}

// pausesLine is one line's pause. A doubtful line is written with doubtful set and no sample; a
// paused line with its sample and no doubtful (FR-552).
type pausesLine struct {
	Cue      string `toml:"cue"`
	Index    int    `toml:"index"`
	Sounds   string `toml:"sounds"`
	Digest   string `toml:"digest"`
	Sample   int    `toml:"sample,omitzero"`
	Doubtful bool   `toml:"doubtful,omitempty"`
}

// LoadPauses reads the shipped pauses, checked against the rules for a book (FR-551).
func LoadPauses() (pause.Book, error) {
	return parsePauses(embeddedPauses)
}

// parsePauses reads pauses from their bytes, refusing a key their shape does not hold and a book the
// rules refuse.
func parsePauses(raw []byte) (pause.Book, error) {
	var parsed pausesFile
	if err := tomlfile.Decode(raw, &parsed); err != nil {
		return pause.Book{}, fmt.Errorf("parsing pauses: %w", err)
	}
	voices := make(map[string]pause.Voice, len(parsed.Voices))
	for id, voice := range parsed.Voices {
		entries := make([]pause.Entry, 0, len(voice.Lines))
		for _, line := range voice.Lines {
			entries = append(entries, pause.Entry{
				Cue: cue.ID(line.Cue), Index: line.Index, Sounds: line.Sounds, Digest: line.Digest,
				Sample: line.Sample, Doubtful: line.Doubtful,
			})
		}
		voices[id] = pause.Voice{Style: voice.Style, Entries: entries}
	}
	return pause.NewBook(parsed.Silence, parsed.Model, voices)
}

// EncodePauses writes a book in the shape pauses.toml holds, under its header: voices sorted, each
// voice's lines in the book's order, so writing the same book again writes the same bytes (FR-551).
// The bytes mean nothing when the error is not nil.
func EncodePauses(book pause.Book) ([]byte, error) {
	file := pausesFile{Silence: book.Silence(), Model: book.Model(), Voices: make(map[string]pausesVoice)}
	for _, id := range book.Voices() {
		voice, _ := book.Voice(id)
		lines := make([]pausesLine, 0, len(voice.Entries))
		for _, entry := range voice.Entries {
			line := pausesLine{
				Cue: string(entry.Cue), Index: entry.Index, Sounds: entry.Sounds, Digest: entry.Digest,
				Sample: entry.Sample, Doubtful: entry.Doubtful,
			}
			if entry.Doubtful {
				line.Sample = 0
			}
			lines = append(lines, line)
		}
		file.Voices[id] = pausesVoice{Style: voice.Style, Lines: lines}
	}
	written, err := tomlfile.Encode(file)
	return append([]byte(pausesHeader), written...), err
}
