package config

import (
	_ "embed"
	"fmt"

	"github.com/oernster/bridge-talk/internal/domain/cue"
	"github.com/oernster/bridge-talk/internal/domain/script"
	"github.com/oernster/bridge-talk/internal/infrastructure/tomlfile"
)

//go:embed sounds.toml
var embeddedSounds []byte

// soundsHeader opens sounds.toml, saying whose file it is and how it is made again.
const soundsHeader = "# The speech sounds of every line in script.toml, made by the sounds tool (FR-532).\n" +
	"# Do not edit this file: change script.toml, then from the repository root run\n" +
	"#   go run ./tools/sounds\n\n"

// soundsFile is the shape of sounds.toml: for each cue, its lines as written when the sounds tool
// ran and their speech sounds in each accent, in the same order.
type soundsFile struct {
	Sounds map[string]soundsEntry `toml:"sounds"`
}

// soundsEntry is one cue's saved speech sounds.
type soundsEntry struct {
	Lines    []string `toml:"lines"`
	British  []string `toml:"british"`
	American []string `toml:"american"`
}

// LoadVoicedScript reads the shipped script with its saved speech sounds, checked against the cue
// table and against each other (FR-532, FR-533).
func LoadVoicedScript(table cue.Table) (script.Voiced, error) {
	return voiceScript(embeddedScript, embeddedSounds, table)
}

// voiceScript reads a script and its saved speech sounds from their bytes, checked against the
// cue table and against each other.
func voiceScript(rawScript, rawSounds []byte, table cue.Table) (script.Voiced, error) {
	loaded, err := parseScript(rawScript, table)
	if err != nil {
		return script.Voiced{}, err
	}
	saved, err := parseSounds(rawSounds)
	if err != nil {
		return script.Voiced{}, err
	}
	return script.Voice(loaded, saved)
}

// parseSounds reads saved speech sounds, refusing a key their shape does not hold.
func parseSounds(raw []byte) (map[string]script.Saved, error) {
	var parsed soundsFile
	if err := tomlfile.Decode(raw, &parsed); err != nil {
		return nil, fmt.Errorf("parsing saved speech sounds: %w", err)
	}
	saved := make(map[string]script.Saved, len(parsed.Sounds))
	for key, entry := range parsed.Sounds {
		saved[key] = script.Saved{Lines: entry.Lines, British: entry.British, American: entry.American}
	}
	return saved, nil
}

// EncodeSounds writes saved speech sounds in the shape sounds.toml holds, under its header. The
// bytes mean nothing when the error is not nil.
func EncodeSounds(saved map[string]script.Saved) ([]byte, error) {
	file := soundsFile{Sounds: make(map[string]soundsEntry, len(saved))}
	for key, entry := range saved {
		file.Sounds[key] = soundsEntry{Lines: entry.Lines, British: entry.British, American: entry.American}
	}
	written, err := tomlfile.Encode(file)
	return append([]byte(soundsHeader), written...), err
}
